services:
  - type: web
    name: atlas-fx-discord-bot
    env: node
    plan: free
    buildCommand: rm -rf node_modules && npm install && npx playwright install chromium
    startCommand: npm start
    autoDeploy: true
